- name: Install packages using APT
  ansible.builtin.apt:
    name:
      - snapd
      - live-build
    state: present

- name: Install ubuntu-image using snap
  community.general.snap:
    name: ubuntu-image
    classic: true

- name: Perform cleanup
  ansible.builtin.import_tasks: clean.yml

- name: Generate the image using ubuntu-image
  ansible.builtin.import_tasks: img.yml

- name: Generate the live installer using live-build
  ansible.builtin.import_tasks: live.yml
